image: node:6.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn install
          - yarn test